name: Blueprint Diff
on: pull_request
jobs:
  blueprint_diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          wget https://github.com/wpengine/atlas-blueprint-portfolio/raw/main/acm-blueprint.zip -O /tmp/acm-blueprint-origin.zip
          unzip /tmp/acm-blueprint-origin.zip

          unzip ./acm-blueprint.zip -d /tmp/acm-blueprint

          echo ::set-output name=version::$(diff --recursive -y --new-file /tmp/acm-blueprint/ /tmp/acm-blueprint-origin/)

          exit 0
