name: Blueprint Diff
on: pull_request
jobs:
  blueprint_diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Check for changes
        id: check-for-export-changes
        run: echo ::set-output name=check::$(git diff --name-only main --exit-code acm-blueprint.zip)
      - name: Setup
        if: steps.check-for-export-changes.outputs.check != 0
        run: |
          wget https://github.com/wpengine/atlas-blueprint-portfolio/raw/main/acm-blueprint.zip -O /tmp/acm-blueprint-origin.zip
          unzip -j /tmp/acm-blueprint-origin.zip -d /tmp/acm-blueprint-origin
          unzip -j ./acm-blueprint.zip -d /tmp/acm-blueprint
      - name: Create Diff
        if: steps.check-for-export-changes.outputs.check != 0
        run: |
          diff -ry --suppress-common-lines /tmp/acm-blueprint-origin/ /tmp/acm-blueprint/ || true > ./diff-output.txt
          cat ./diff-output.txt
      - name: Create artifact
        if: steps.check-for-export-changes.outputs.check != 0
        uses: actions/upload-artifact@v3
        with:
          name: Blueprint export diff
          path: ./diff-output.txt
